name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          
      - name: Configure Poetry
        run: |
          poetry config repositories.github https://github.com/CubeVic/configuration_loader
          poetry config http-basic.github ${{ github.actor }} ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and publish
        run: |
          poetry build
          poetry publish -r github